url: soonermillworksandrenovation.com
baseurl: /

# Site settings
title: SECTION_1
email: boomersoonerdave@yahoo.com
description: "SECTION_2"


# Team names, titles and social links
people:
- name: STAFF_1
  pic: 1
  position: POSITION_1
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: STAFF_2
  pic: 2
  position: POSITION_2
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: STAFF_3
  pic: 3
  position: POSITION_3
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url: #
  - title: github
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: ADDRESS_1
  - line: ADDRESS_2

# Build settings
markdown: kramdown
permalink: pretty
